[project]
name = "assignment1-embedding-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "en-core-web-lg",
    "fastapi[standard]>=0.141.1",
    "pillow>=12.3.0",
    "python-multipart>=0.0.32",
    "spacy>=3.8.16",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
    "uvicorn[standard]>=0.53.0",
]

[tool.uv.sources]
en-core-web-lg = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl" }
torch = { index = "pytorch-cpu", marker = "sys_platform == 'linux'" }
torchvision = { index = "pytorch-cpu", marker = "sys_platform == 'linux'" }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true